training:
  scheduler:
    class_path: core.schedulers.DDPMScheduler
    init_args:
      num_train_timesteps: 1000
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: linear
      trained_betas: null
      variance_type: fixed_large
      clip_sample: true
      prediction_type: epsilon
      thresholding: false
      dynamic_thresholding_ratio: 0.995
      clip_sample_range: 1.0
      sample_max_value: 1.0
      timestep_spacing: trailing
      steps_offset: 0
      rescale_betas_zero_snr: false
  ema_decay: 0.9999
  learning_rate: 1.2e-4

inference:
  scheduler: null
  num_samples: 1024
  pipeline_kwargs:
    batch_size: 256
    num_inference_steps: 1000