defaults:
  - model: diffusers_native
  - data: cifar10
  - scheduler@training.scheduler: ddpm
  - scheduler@inference.scheduler: ddpm
  - logger: wandb
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: ./

resume_from_checkpoint: null

pl_trainer:
  precision: "16-mixed"
  strategy: ddp
  num_sanity_val_steps: 0
  max_epochs: ${training.epochs}
  enable_model_summary: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  devices: -1

data:
  image_resolution: 32
  batch_size: ${training.batch_size}

inference:
  batch_size: 256
  num_inference_steps: 1000
  num_samples: 1024

training:
  batch_size: 128
  learning_rate: 1.e-4
  epochs: 3000
  ema_decay: 0.9999 # `-1` disables it